spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/sharp-demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: jkxyx205
  mail:  # SMTP 发邮件
    host: smtp.qiye.aliyun.com
    port: 25
    username: xxx
    password: xxx
    default-encoding: UTF-8
    imap: # IMAP 收邮件
      host: imap.qiye.aliyun.com
      port: 143
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    com.rick.demo: DEBUG
    com.rick.db: DEBUG

#sharp:
#  database:
#    select-cache: true
formflow:
  form:
    insertCpnValue: false

dict:
  items:
    - type: user
      sql: "select username, name from sys_user order by id asc"
    - type: grade
      map: {g1: "一年级", g2: "二年级"}

fileupload:
  tmp: /Users/rick/jkxyx205/tmp/fastdfs/tmp # 下载的临时目录
  local: # cd /Users/rick/jkxyx205/tmp/fileupload && http-server -p 7892
    root-path: /Users/rick/jkxyx205/tmp/fileupload
    server-url: http://localhost:7892/ # 映射到tmp目录
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: xxx
    accessKeySecret: xxx
    bucketName: sharp-fileupload

