spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/sharp-demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: jkxyx205
  mail:  # SMTP 发邮件
    host: smtp.qiye.aliyun.com
    port: 25
    username: xxx
    password: xxx
    default-encoding: UTF-8
    imap: # IMAP 收邮件
      host: imap.qiye.aliyun.com
      port: 143
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    com.rick.demo: DEBUG
    com.rick.db: DEBUG

sharp:
  database:
    select-cache: false
    init-database-meta-data: true
    entity-base-package: com.rick.demo.module.**.entity

dict:
  items:
    - type: user
      sql: "select username, name from sys_user order by id asc"
    - type: grade
      map: {g1: "一年级", g2: "二年级"}
    - type: bol
      map: { "1" : "是", "0": "否" }
    - type: status
      map: {LOCKED: "锁定", NORMAL: "正常"}
    - type: nativePlace #  有中文不能使用 map: { "江苏": "江苏", "四川": "四川", "陕西": "陕西", "上海": "上海" }
      list:
        - "江苏"
        - "四川"
        - "陕西"
        - "上海"
props:
  items: {"s1": "helloworld"}

fileupload:
  tmp: /Users/rick/Space/tmp/fastdfs/tmp # 下载的临时目录
  local: # cd /Users/rick/Space/tmp/fileupload && http-server -p 7892
    root-path: /Users/rick/Space/tmp/fileupload
    server-url: http://localhost:7892/ # 映射到tmp目录
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: xxx
    accessKeySecret: xxx
    bucketName: sharp-fileupload

#bark:
#  url: https://bark-worker.jkxyx205.workers.dev
#  device-keys:
#    - xxx

bark:
  url: https://api.day.app # 这个地址不允许批量发送消息
  device-key: xxx
wechat:
  appid:  xxx
  secret: xxx