spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fastdfs?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: jkxyx205
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
fileupload:
  tmp: /Users/rick/Space/tmp/fastdfs/tmp # 下载的临时目录
  local:
#    cd /Users/rick/Space/tmp/fileupload
#    http-server -p 7892
    server-url: http://localhost:7892/ # 映射到tmp目录
    root-path: /Users/rick/Space/tmp/fileupload #

  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: xxx
    accessKeySecret: xxx
    bucketName: sharp-fileupload
