server:
  port: 8080
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 容器中运行
      url: jdbc:mysql://db:3306/sharp-admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
      initialSize: 1
      minIdle: 5
      maxActive: 10
      maxWait: 60000

logging:
  file:
    path: /opt/app/log

fileupload:
  tmp: /opt/app/tmp # 下载的临时目录
  local: # cd /Users/rick/Space/tmp/fileupload && http-server -p 7892
    root-path: /opt/app/files
    server-url: http://114.55.173.102:8786/ # 映射到tmp目录