server:
  port: 8080
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sharp-admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: jkxyx205
      initialSize: 1
      minIdle: 5
      maxActive: 10
      maxWait: 60000

logging:
  file:
    path: /Users/rick/Space/tmp/admin/log

fileupload:
  tmp: E:\\project\\py\\tmp # 下载的临时目录
  local: # cd /Users/rick/Space/tmp/fileupload && http-server -p 7892
    root-path: E:\\project\\py\\files
    server-url: http://114.55.173.102:8786/ # 映射到tmp目录