server:
  port: 8090

spring:
  profiles:
    active: dev
#  datasource:
#    hikari:
#      username: root
#      password: jkxyx205
#    url: jdbc:mysql://localhost:3306/jzsoft?useSSL=false&useUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.mysql.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 2fc27dbe786869f767ef
            client-secret: 903855737c67f413746b14d3eeefd78ffcb2bece
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8090/login/oauth2/code/github"
            scope: user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token

sharp:
  security:
    code:
      sms:
        length: 8

