server:
  port: 8081
  servlet:
    context-path: /resource-server-jwt


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:key.public
          jws-algorithm: RS512
